bucket               = "ep-eks-state-store"
key                  = "terraform.tfstate"
region               = "us-east-1"
workspace_key_prefix = "environment"
dynamodb_table       = "ep-eks-state-lock"